name: Cleanup Docker Images

on:
  schedule:
    # Run on the 15th of every month at midnight UTC
    - cron: '0 0 15 * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  packages: write

jobs:
  cleanup-ghcr:
    name: Cleanup GHCR Images
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: podgrab
          owner: ${{ github.repository_owner }}
          delete-untagged: true
          delete-partial-images: true
          keep-n-tagged: 3
          older-than: 30 days
          dry-run: false
